<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-V52KHLDN" failures="1" tests="11" name="myTest" time="60.345" errors="0" timestamp="2025-01-23T16:31:17 IST">
  <testcase classname="tests.DashboardTest" name="verifyDashboardHeader" time="0.442"/>
  <testcase classname="tests.DashboardTest" name="clickProfileDropDownMethod" time="2.224"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem1" time="0.042"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem2" time="0.04"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem3" time="0.166"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem4" time="0.145"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem4Er" time="0.178">
    <failure type="java.lang.AssertionError" message="Item4 mismatch expected [Logoutss] but found [Logout]">
      <![CDATA[java.lang.AssertionError: Item4 mismatch expected [Logoutss] but found [Logout]
at tests.DashboardTest.verifyDropdownItem4Er(DashboardTest.java:71)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyDropdownItem4Er -->
  <testcase classname="tests.LoginTest" name="loginwithValidCreds" time="0.745"/>
  <testcase classname="tests.LoginTest" name="loginwithValidCreds" time="1.965"/>
  <testcase classname="tests.LoginTest" name="loginwithInvalidCreds" time="2.106"/>
  <testcase classname="tests.LoginTest" name="loginwithInvalidCreds" time="3.602"/>
</testsuite> <!-- myTest -->
