<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-V52KHLDN" failures="1" tests="7" name="tests.DashboardTest" time="3.268" errors="0" timestamp="2025-01-22T12:12:21 IST" skipped="0">
  <testcase classname="tests.DashboardTest" name="verifyDashboardHeader" time="0.489"/>
  <testcase classname="tests.DashboardTest" name="clickProfileDropDownMethod" time="2.236"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem1" time="0.048"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem2" time="0.050"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem3" time="0.142"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem4" time="0.138"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem4Er" time="0.165">
    <failure message="Item4 mismatch expected [Logoutss] but found [Logout]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Item4 mismatch expected [Logoutss] but found [Logout]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at tests.DashboardTest.verifyDropdownItem4Er(DashboardTest.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
at java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:151)
at org.testng.internal.thread.graph.TestNGFutureTask.<init>(TestNGFutureTask.java:15)
at org.testng.internal.thread.graph.GraphOrchestrator.runNodes(GraphOrchestrator.java:58)
at org.testng.internal.thread.graph.GraphOrchestrator.afterExecute(GraphOrchestrator.java:87)
at org.testng.internal.thread.graph.TestNGFutureTask.done(TestNGFutureTask.java:34)
at java.base/java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:434)
at java.base/java.util.concurrent.FutureTask.set(FutureTask.java:285)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:325)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
at java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:151)
at org.testng.internal.thread.graph.TestNGFutureTask.<init>(TestNGFutureTask.java:15)
at org.testng.internal.thread.graph.GraphOrchestrator.runNodes(GraphOrchestrator.java:58)
at org.testng.internal.thread.graph.GraphOrchestrator.run(GraphOrchestrator.java:46)
at org.testng.TestTaskExecutor.execute(TestTaskExecutor.java:69)
at org.testng.TestRunner.privateRun(TestRunner.java:720)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- verifyDropdownItem4Er -->
</testsuite> <!-- tests.DashboardTest -->
